### ISSUE TITLE
Change `active-if` helper to be generic `class-if`

### ISSUE THREAD

**Issue by rudiv** [cedita/Coda#2]
Rather than:

    <li class="nav-item" active-if-controller="Home"> ... </li>

Allow the following:

    <li class="nav-item" class-if-value="active" class-if-controller="Home">

This allows the Tag Helper to be used on any element.

**Comment by Turv** [comment]
That is a much better syntax

**Comment by rudiv** [comment]
This is completed, the `active-if` helpers will no longer work. Updating docs now.
